### ISSUE TITLE
在Linux上运行报错

### ISSUE THREAD

**Issue by kemomi** [TheKOG/Gal-Voice-Bot#2]
File "bot.py", line 4, in <module>
    import nonebot
ImportError: No module named nonebot

**Comment by TheKOG** [comment]
请参考https://v2.nonebot.dev/docs/start/installation

**Comment by DLW3D** [comment]
安装nonebot2后依然报错
```
Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter
ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
```

编辑：是还需要安装onebot适配器：
`nb adapter install nonebot-adapter-onebot`

**Comment by KafuuEriri** [comment]
```
nb adapter install
OneBot V11
```
再装一下协议适配器

**Comment by AtoriUzawa** [comment]
Failed to import "atri_voice"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/bot.linux/bot.py", line 16, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bot.linux/plugins/atri_voice/__init__.py", line 8, in <module>
    import VITS
  File "/home/ubuntu/bot.linux/VITS/__init__.py", line 8, in <module>
    from .text import text_to_sequence
  File "/home/ubuntu/bot.linux/VITS/text/__init__.py", line 2, in <module>
    from . import cleaners
  File "/home/ubuntu/bot.linux/VITS/text/cleaners.py", line 17, in <module>
    import pyopenjtalk
  File "/home/ubuntu/bot.linux/pyopenjtalk/__init__.py", line 20, in <module>
    from .htsengine import HTSEngine
ModuleNotFoundError: No module named 'pyopenjtalk.htsengine'

**Comment by INSide-734** [comment]
> File "bot.py", line 4, in import nonebot ImportError: No module named nonebot

是缺少nonebot不是nonebot2吧qwq？

**Comment by kemomi** [comment]
不是nb2

**Comment by int-PP** [comment]
> 安装nonebot2后依然报错
> 
> ```
> Traceback (most recent call last):
>   File "bot.py", line 5, in <module>
>     from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter
> ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 编辑：是还需要安装onebot适配器： `nb adapter install nonebot-adapter-onebot`

直接pip install nonebot-adapter-onebot安装OneBot V11的适配器

**Comment by int-PP** [comment]
> 安装nonebot2后依然报错
> 
> ```
> Traceback (most recent call last):
>   File "bot.py", line 5, in <module>
>     from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter
> ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
> ```
> 
> 编辑：是还需要安装onebot适配器： `nb adapter install nonebot-adapter-onebot`

不是nb2的这是nb1
